spring.application.name=backend

# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
assetvault.app.jwtSecret=${JWT_SECRET}
assetvault.app.jwtExpirationMs=86400000

# CORS Configuration
app.cors.allowed-origins=${FRONTEND_URL}
